import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  quickLookupCard: {
    padding: 20,
    backgroundColor: '#ffffff',
    borderRadius: 20,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: '#e2e8f0',
    marginBottom: 24,
  },
  quickLookupHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  quickLookupTitle: {
    fontWeight: '700',
    fontSize: 18,
    color: '#0f172a',
  },
  quickLookupInfoButton: {
    width: 28,
    height: 28,
    borderRadius: 14,
    borderWidth: 1.5,
    borderColor: '#cbd5e1',
    backgroundColor: '#f8fafc',
    justifyContent: 'center',
    alignItems: 'center',
  },
  quickLookupInfoLabel: {
    fontWeight: '700',
    fontSize: 14,
    color: '#64748b',
  },
  quickLookupInput: {
    borderWidth: 1,
    borderColor: '#cbd5e1',
    borderRadius: 12,
    paddingVertical: 14,
    paddingHorizontal: 16,
    fontSize: 15,
    color: '#0f172a',
    backgroundColor: '#f8fafc',
    minHeight: 72,
    marginBottom: 12,
  },
  quickLookupActions: {
    flexDirection: 'row',
    gap: 10,
  },
  quickLookupButton: {
    flex: 1,
    backgroundColor: '#3b82f6',
    borderRadius: 8,
    paddingVertical: 10,
    paddingHorizontal: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  quickLookupButtonLabel: {
    color: '#ffffff',
    fontWeight: '600',
    fontSize: 14,
  },
  quickLookupCalendarButton: {
    flex: 1,
    flexDirection: 'row',
    gap: 8,
    backgroundColor: '#1e293b',
    borderRadius: 8,
    paddingVertical: 10,
    paddingHorizontal: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  quickLookupCalendarButtonDisabled: {
    opacity: 0.6,
  },
  quickLookupCalendarButtonPressed: {
    opacity: 0.85,
  },
  quickLookupCalendarButtonLabel: {
    color: '#ffffff',
    fontWeight: '600',
    fontSize: 14,
  },
  quickLookupHint: {
    marginTop: 12,
    fontSize: 13,
    color: '#64748b',
    lineHeight: 18,
  },
  error: {
    marginTop: 10,
    padding: 12,
    backgroundColor: '#fee2e2',
    borderRadius: 8,
    color: '#b91c1c',
    fontSize: 14,
    fontWeight: '500',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(15, 23, 42, 0.75)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 24,
  },
  modalContent: {
    width: '100%',
    maxWidth: 400,
    backgroundColor: '#ffffff',
    borderRadius: 20,
    padding: 24,
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: '#0f172a',
    marginBottom: 12,
  },
  modalBody: {
    fontSize: 15,
    lineHeight: 22,
    color: '#475467',
    marginBottom: 20,
  },
  modalCloseButton: {
    backgroundColor: '#2563eb',
    borderRadius: 12,
    paddingVertical: 14,
    alignItems: 'center',
  },
  modalCloseButtonLabel: {
    color: '#ffffff',
    fontWeight: '600',
    fontSize: 16,
  },
});
